"""
This file defines the message codes for multilanguage in the frontend
Using i18n standard, please check multilanguage folder to add or modify messages
assets/i18n/<lang>
"""

# Common Messages
OK_MSG = "OK_MSG"
CREATED_MSG = "CREATED_MSG"
NOT_FOUND_MSG = "NOT_FOUND_MSG"
CONFLICT_MSG = "CONFLICT_MSG"
UNPROCESSABLE_ENTITY_MSG = "UNPROCESSABLE_ENTITY_MSG"
INTERNAL_SERVER_ERROR_MSG = "INTERNAL_SERVER_ERROR_MSG"
SERVER_TIMEOUT_MSG = "SERVER_TIMEOUT_MSG"
NO_DATA = "NO_DATA"
NO_FIELDS_TO_UPDATE = "NO_FIELDS_TO_UPDATE"

# Common Validations Messages
INVALID_ID = "INVALID_ID"  # Invalid Id

# Health Validations Messages
HEALTH_NOT_FOUND = "HEALTH_NOT_FOUND"  # Health not found
HEALTH_SUCCESSFULLY = "HEALTH_SUCCESSFULLY"  # Health successfully responded

# ZONE Validations Messages
ZONE_NOT_FOUND = "ZONE_NOT_FOUND"  # Zone not found
ZONE_SUCCESSFULLY_UPDATED = "ZONE_SUCCESSFULLY_UPDATED"  # Zone successfully updated
ZONE_SUCCESSFULLY_DELETED = "ZONE_SUCCESSFULLY_DELETED"  # Zone successfully deleted
ZONE_SUCCESSFULLY_CREATED = "ZONE_SUCCESSFULLY_CREATED"  # Zone created successfully
ZONE_DELETE_HAS_RELATIONS = "ZONE_DELETE_HAS_RELATIONS"  # Zone cannot be deleted, has relationships with some categories
ZONE_ALREADY_EXIST = "ZONE_ALREADY_EXIST"  # Zone already exist from database
ZONE_NAME_REQUIRED = "ZONE_NAME_REQUIRED"  # Required id zone name
ZONE_LOCATION_REQUIRED = "ZONE_LOCATION_REQUIRED"  # Required rid zone location
INCORRECT_REQUEST_PARAM = "COLUMN_NOT_FOUND"
ERROR_DELETE = "ERROR_DELETE"  # Error deleting zone by id
ZONE_ITEM_NOT_FOUND = "ZONE_ITEM_NOT_FOUND"  # Zone item not found

# Lost Objects Validation Messages
LOST_OBJECTS_NOT_FOUND = "LOST_OBJECTS_NOT_FOUND"
LOST_OBJECTS_FOUND = "LOST_OBJECTS_FOUND"
LOST_OBJECTS_SUCCESSFULLY_CREATED = "LOST_OBJECTS_SUCCESSFULLY_CREATED"
LOST_OBJECT_SUCCESSFULLY_DELETED = "LOST_OBJECT_SUCCESSFULLY_DELETED"
LOST_OBJECTS_NAME_REQUIRED = "LOST_OBJECTS_NAME_REQUIRED"
LOST_OBJECTS_DESCRIPTION_REQUIRED = "LOST_OBJECTS_DESCRIPTION_REQUIRED"
LOST_OBJECTS_SAFEKEEPER_REQUIRED = "LOST_OBJECTS_SAFEKEEPER_REQUIRED"
LOST_OBJECTS_USER_EMAIL_REQUIRED = "LOST_OBJECTS_USER_EMAIL_REQUIRED"
INVALID_EMAIL_DOMAIN = "INVALID_EMAIL_DOMAIN"
INCORRECT_REQUEST_PARAM='COLUMN_NOT_FOUND'
NO_ITEMS_TO_UPDATE = 'NO_ITEMS_TO_UPDATE'


# CATEGORY Validation Messages
CATEGORY_NOT_FOUND = "CATEGORY_NOT_FOUND"
CATEGORY_SUCCESSFULLY_UPDATED = "CATEGORY_SUCCESSFULLY_UPDATED"
CATEGORY_SUCCESSFULLY_DELETED = "CATEGORY_SUCCESSFULLY_DELETED"
CATEGORY_SUCCESSFULLY_CREATED = "CATEGORY_SUCCESSFULLY_CREATED"
CATEGORY_DELETE_HAS_RELATIONS = "CATEGORY_DELETE_HAS_RELATIONS"
CATEGORY_ALREADY_EXISTS = "CATEGORY_ALREADY_EXISTS"
EMPTY_CATEGORY_NAME = "EMPTY_CATEGORY_NAME"
LOST_OBJECTS_CATEGORY_REQUIRED = "LOST_OBJECTS_CATEGORY_REQUIRED"
INVALID_DATE_FORMAT = "INVALID_DATE_FORMAT"
UPDATE_SUCCESS = "UPDATE_SUCCESS"
NO_CHANGES = "NO_CHANGES"
UNAUTHORIZED = 'UNAUTHORIZED'
FORBIDDEN = 'FORBIDDEN'
INTERNAL_SERVER_ERROR = 'INTERNAL_SERVER_ERROR'
AUTH_TOKEN_REQUIRED = 'AUTH_TOKEN_REQUIRED'
AUTH_REQUEST_ERROR = 'AUTH_REQUEST_ERROR'
PERMISSION_DENIED = 'PERMISSION_DENIED'
AUTH_PROCESSING_ERROR = 'AUTH_PROCESSING_ERROR'
INVALID_RESPONSE_FORMAT = 'INVALID_RESPONSE_FORMAT'
AUTH_FAILED = 'AUTH_FAILED'
INVALID_REQUEST_PARAM = 'INVALID_REQUEST_PARAM'